@host = http://localhost:3000
@api = {{host}}/api/user
@id = 6a5aed7cb1ee0a734aa9ff05
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjZhNWFlZDdjYjFlZTBhNzM0YWE5ZmYwNSIsIm5hbWUiOiJBbGVqYW5kcm8iLCJzdXJuYW1lIjoiQ2FzdHJvIEMiLCJuaWNrIjoieGFuZHJvZGV2IiwiZW1haWwiOiJ4YW5kcm9AZXhhbXBsZS5jb20iLCJiaW8iOiJOdWV2YSBiaW9ncmFmw61hIiwiYXZhdGFyIjoiZGVmYXVsdC5wbmciLCJpYXQiOjE3ODQ2MDIyNTMsImV4cCI6MTc4NzE5NDI1M30.VVul1NcWD082wGbLyplTWVJoX5xa03jweYRjmbwsW7w
### ============================================
### Registrar usuario
### ============================================
POST {{api}}/register
Content-Type: application/json

{
  "name": "Alejandro",
  "surname": "Salazar",
  "nick": "xandro",
  "email": "xandro@example.com",
  "password": "12345678",
  "bio": "Desarrollador Backend con Node.js",
  "extra": true
}

###

### ============================================
### Login
### ============================================
POST {{api}}/login
Content-Type: application/json

{
  "email": "xandro@example.com",
  "password": "12345678"
}

###

### ============================================
### prueba JWT
### ============================================
GET {{api}}/pruebajwt
Authorization: Bearer {{token}}

###

### ============================================
### Obtener perfil
### ============================================
GET {{api}}/profile/{{id}}

###

### ============================================
### Actualizar usuario
### ============================================
PUT {{api}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alejandro",
  "surname": "Castro C",
  "nick": "xandrodev",
  "email": "xandro@example.com",
  "bio": "Nueva biografía"
}

###

### ============================================
### Subir avatar
### ============================================
PUT {{api}}/upload/{{id}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file0"; filename="avatar.png"
Content-Type: image/png

< /home/xandro/Imágenes/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
ID=6a5aed7cb1ee0a734aa9ff05
TOKEN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjZhNWFlZDdjYjFlZTBhNzM0YWE5ZmYwNSIsIm5hbWUiOiJBbGVqYW5kcm8iLCJzdXJuYW1lIjoiQ2FzdHJvIEMiLCJuaWNrIjoieGFuZHJvZGV2IiwiZW1haWwiOiJ4YW5kcm9AZXhhbXBsZS5jb20iLCJiaW8iOiJOdWV2YSBiaW9ncmFmw61hIiwiYXZhdGFyIjoiZGVmYXVsdC5wbmciLCJpYXQiOjE3ODQ2MDIyNTMsImV4cCI6MTc4NzE5NDI1M30.VVul1NcWD082wGbLyplTWVJoX5xa03jweYRjmbwsW7w"
IMG="$HOME/Imágenes/gato/f02.png"

curl -X PUT \
  -H "Authorization: Bearer $TOKEN" \
  -F "file0=@$IMG" \
  "http://localhost:3000/api/user/upload/$ID" | jq

### ============================================
### Obtener avatar
### ============================================
GET {{api}}/avatar/avatar-1784608182749-f02.png
