@host = http://localhost:3000
@api = {{host}}/api/user
@id = 6a5aed7cb1ee0a734aa9ff05
@token = eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6IjZhNWFlZDdjYjFlZTBhNzM0YWE5ZmYwNSIsIm5hbWUiOiJBbGVqYW5kcm8iLCJzdXJuYW1lIjoiU2FsYXphciIsIm5pY2siOiJ4YW5kcm8iLCJlbWFpbCI6InhhbmRyb0BleGFtcGxlLmNvbSIsImJpbyI6IkRlc2Fycm9sbGFkb3IgQmFja2VuZCBjb24gTm9kZS5qcyIsImF2YXRhciI6ImRlZmF1bHQucG5nIiwiaWF0IjoxNzg0NTE2Nzk3LCJleHAiOjE3ODcxMDg3OTd9.KNrAI2z5M6Ob7VMf7F7Z9PtQR8KsEblh1Cp70vd2jYM
### ============================================
### Registrar usuario
### ============================================
POST {{api}}/register
Content-Type: application/json

{
  "name": "Alejandro",
  "surname": "Salazar",
  "nick": "xandro",
  "email": "xandro@example.com",
  "password": "12345678",
  "bio": "Desarrollador Backend con Node.js",
  "extra": true
}

###

### ============================================
### Login
### ============================================
POST {{api}}/login
Content-Type: application/json

{
  "email": "xandro@example.com",
  "password": "12345678"
}

###

### ============================================
### prueba JWT
### ============================================
GET {{api}}/pruebajwt
Authorization: Bearer {{token}}

###

### ============================================
### Obtener perfil
### ============================================
GET {{api}}/profile/{{id}}

###

### ============================================
### Actualizar usuario
### ============================================
PUT {{api}}/update
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Alejandro",
  "surname": "Castro C",
  "nick": "xandrodev",
  "email": "xandro@example.com",
  "bio": "Nueva biografía"
}

###

### ============================================
### Subir avatar
### ============================================
PUT {{api}}/upload/{{id}}
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file0"; filename="avatar.png"
Content-Type: image/png

< /home/xandro/Imágenes/avatar.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
ID=6884e2a5a9d35c51cb2d3d8a
TOKEN="TU_TOKEN"
IMG="$HOME/Imágenes/avatar.png"

curl -X PUT \
  -H "Authorization: Bearer $TOKEN" \
  -F "file0=@$IMG" \
  "http://localhost:3000/api/user/upload/$ID"

### ============================================
### Obtener avatar
### ============================================
GET {{api}}/avatar/default.png
